In [4]:

# tf.layers.BatchNormalization和tf.layers.batch_normalization实际上是一个东西，只不过后者是一个函数，对前者又包裹了一层
# 底层调用的还是keras的BN
import tensorflow as tf
import numpy as np

tf.reset_default_graph()
input_arr=np.reshape(np.arange(0,72),newshape=[2,3,3,4]).astype(np.float32)
input_tensor=tf.constant(input_arr)

bn_layer=tf.layers.BatchNormalization(axis=-1,momentum=0.1) # 把动量设小点，让moving mean变化剧烈一些，从而观察效果
output=bn_layer(input_tensor,training=True)
update_ops=tf.get_collection(tf.GraphKeys.UPDATE_OPS) # 这个update操作需要定义在bn_layer的call之后，否则会为空

test_output=bn_layer(input_tensor,training=False)

print(bn_layer.weights)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output_v=sess.run(output)
    print("\ntraining output")
    print(output_v)
    print("\nweights before update")
    print(sess.run(bn_layer.weights))
    sess.run(update_ops)
    print("\nweights after update")
    print(sess.run(bn_layer.weights))
    print("\nnot training output")
    test_output_v=sess.run(test_output)
    print(test_output_v)

[<tf.Variable 'batch_normalization/gamma:0' shape=(4,) dtype=float32_ref>, <tf.Variable 'batch_normalization/beta:0' shape=(4,) dtype=float32_ref>, <tf.Variable 'batch_normalization/moving_mean:0' shape=(4,) dtype=float32_ref>, <tf.Variable 'batch_normalization/moving_variance:0' shape=(4,) dtype=float32_ref>]

training output
[[[[-1.6383542  -1.6383542  -1.6383542  -1.6383542 ]
   [-1.4456066  -1.4456066  -1.4456066  -1.4456066 ]
   [-1.2528591  -1.2528591  -1.2528591  -1.2528591 ]]

  [[-1.0601115  -1.0601115  -1.0601115  -1.0601115 ]
   [-0.867364   -0.867364   -0.867364   -0.867364  ]
   [-0.6746164  -0.6746164  -0.6746164  -0.6746164 ]]

  [[-0.48186886 -0.48186886 -0.48186886 -0.48186886]
   [-0.28912133 -0.28912133 -0.28912133 -0.28912133]
   [-0.09637377 -0.09637377 -0.09637377 -0.09637377]]]


 [[[ 0.09637377  0.09637377  0.09637377  0.09637377]
   [ 0.28912133  0.28912133  0.28912133  0.28912133]
   [ 0.48186886  0.48186886  0.48186886  0.48186886]]

  [[ 0.6746164   0.674616