In [11]:
# 如果某个神经元的输出恒定为0，那么损失对该神经元之后的1个的参数和之前的所有参数的梯度都是0
import tensorflow as tf
w1 = tf.Variable(tf.random.normal((3, 2)), name='w1')
b1 = tf.Variable(tf.ones(2, dtype=tf.float32), name='b1')

w2 = tf.Variable(tf.random.normal((2, 2)), name='w1')
b2 = tf.Variable(tf.ones(2, dtype=tf.float32), name='b1')
x = [[1., 2., 3.]]
with tf.GradientTape() as tape:
    y1=tf.matmul(x,w1)+b1
    y2=tf.multiply(y1,[1,0])
    y3=tf.matmul(y2,w2)+b2
    dw1,dw2=tape.gradient(y3,[w1,w2])
print(y1)
print(y2)
print(dw1)
print(dw2)


tf.Tensor([[5.18154   5.4293575]], shape=(1, 2), dtype=float32)
tf.Tensor([[5.18154 0.     ]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[0.19052559 0.        ]
 [0.38105118 0.        ]
 [0.5715768  0.        ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[5.18154 5.18154]
 [0.      0.     ]], shape=(2, 2), dtype=float32)
