In [6]:
# 简单使用
import numpy as np
import tensorflow as tf

y_logits=np.random.random(size=[4,3])
y_softmax=tf.nn.softmax(y_logits,axis=-1)
# y_true不需要one-hot
y_true=np.array([1,2,0,1])
loss_calculator=tf.keras.losses.SparseCategoricalCrossentropy()
loss_calculator(y_true=y_true,y_pred=y_softmax)

<tf.Tensor: shape=(), dtype=float64, numpy=1.1612266302108765>

In [7]:
# from_logits用法，即不需要手动写一个softmax
loss_calculator=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_calculator(y_true=y_true,y_pred=y_logits)


<tf.Tensor: shape=(), dtype=float64, numpy=1.1612266302108765>

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[0.28298815, 0.29733949, 0.41967236],
       [0.48900825, 0.31601124, 0.19498051],
       [0.49659089, 0.25120752, 0.25220159],
       [0.33494951, 0.33381064, 0.33123985]])>