In [2]:
# make one shot iterator
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
ds=tf.data.Dataset.from_tensor_slices(np.reshape(np.arange(0,20),newshape=[2,10]).astype(np.float32))
iterator=sample_data=ds.make_one_shot_iterator()
sample_data=iterator.get_next()
with tf.Session() as sess:
    print(sess.run([sample_data]))
    print(sess.run([sample_data]))
    print(sess.run([sample_data]))

[array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)]
[array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.], dtype=float32)]


OutOfRangeError: End of sequence
	 [[node IteratorGetNext (defined at <ipython-input-2-3c8e6eecdedd>:8)  = IteratorGetNext[output_shapes=[[10]], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]

Caused by op 'IteratorGetNext', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3c8e6eecdedd>", line 8, in <module>
    sample_data=iterator.get_next()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node IteratorGetNext (defined at <ipython-input-2-3c8e6eecdedd>:8)  = IteratorGetNext[output_shapes=[[10]], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]


In [3]:
# make initializable iterator
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
ds=tf.data.Dataset.from_tensor_slices(np.reshape(np.arange(0,20),newshape=[2,10]).astype(np.float32))
iterator=sample_data=ds.make_initializable_iterator()
sample_data=iterator.get_next()
with tf.Session() as sess:
    sess.run(iterator.initializer)
    print(sess.run([sample_data]))
    sess.run(iterator.initializer)
    print(sess.run([sample_data]))

[array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)]
[array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)]


In [62]:
import tensorflow as tf
tf.reset_default_graph()
print(tf.__version__)
# 在tf1之中配合dataset对multihot样本进行embedding
# 注意featureId一定要从0开始，否则转稀疏矩阵时会丢到该值
num_fields=3
num_features=8
raw_ds=tf.data.Dataset.from_tensor_slices(["1:1 2:3;4 3:6","1:2 2:5 3:7","1:1 2:4 3:7"])

def line_tf_parser(line):
    """

    :param line: tensor in string
    :return: 返回的是一个list，每个元素都是一个field的feature_id字符串，用;连接
         不借助py_function的方法
         输出是一个tensor，shape为[num_fields]
    """
    row=tf.strings.split([line]," ") # 稀疏tensor， values就是[1:1,2:3;4]
    field_features=tf.strings.split(row.values,":")  # 稀疏tensor， values就是[1,1,2,3;4]
    field_features=tf.reshape(field_features.values,shape=[num_fields,2]) # reshape一下，使得field_features[0,0:2]代表fieldid和rawfeatureid，例如【2，3；4】
    raw_features=tf.slice(field_features,begin=[0,1],size=[num_fields,1]) # 切片，不要第一列
    # raw_features = tf.strings.split(raw_features,";")
    # raw_features = tf.string.to_number(raw_features,tf.int64)
    return tf.reshape(raw_features,shape=[-1])

raw_fields_ds=raw_ds.map(line_tf_parser)
raw_fields_iter=raw_fields_ds.make_initializable_iterator()
raw_fields_item=raw_fields_iter.get_next()

raw_fields_batched_ds=raw_fields_ds.batch(2)
raw_fields_batched_iter=raw_fields_batched_ds.make_initializable_iterator()
raw_fields_batch=raw_fields_batched_iter.get_next() # shape为[batch_size,num_fields]的item，类型string类型

emb_table=tf.get_variable("emb_table",shape=[num_features,4],initializer=tf.truncated_normal_initializer)


def emb_layer(raw_batch):
    embs=list()
    raw_fields = list()
    for i in range(num_fields):
        raw_field_i=raw_batch[:,i]
        raw_field_i=tf.strings.split(raw_field_i,";")
        raw_fields.append(raw_field_i)

        field_i_features = tf.SparseTensor(indices=raw_field_i.indices,values=tf.strings.to_number(raw_field_i.values,tf.int64),
                                           dense_shape=raw_field_i.dense_shape)
        embs.append(tf.nn.embedding_lookup_sparse(params=emb_table,sp_ids=field_i_features,sp_weights=None))
    emb=tf.stack(embs,axis=1)
    return raw_fields,embs,emb

raw_fields,embs,emb=emb_layer(raw_fields_batch)

with tf.Session() as sess:
    sess.run(raw_fields_iter.initializer)
    sess.run(raw_fields_batched_iter.initializer)
    sess.run(tf.global_variables_initializer())
    raw_fields_v,embs_v,emb_v=sess.run([raw_fields,embs,emb])
    print(raw_fields_v)
    print(embs_v)
    print(emb_v)



1.15.2
[SparseTensorValue(indices=array([[0, 0],
       [1, 0]]), values=array([b'1', b'2'], dtype=object), dense_shape=array([2, 1])), SparseTensorValue(indices=array([[0, 0],
       [0, 1],
       [1, 0]]), values=array([b'3', b'4', b'5'], dtype=object), dense_shape=array([2, 2])), SparseTensorValue(indices=array([[0, 0],
       [1, 0]]), values=array([b'6', b'7'], dtype=object), dense_shape=array([2, 1]))]
[array([[-1.8911963 ,  1.6723684 ,  0.2148818 ,  0.35627836],
       [-1.3813689 ,  0.5488272 ,  1.9147371 , -0.3831436 ]],
      dtype=float32), array([[ 0.11691725,  0.23798639, -0.00921731, -0.94440436],
       [-0.39179605,  0.13240324,  1.5920373 ,  0.18155167]],
      dtype=float32), array([[ 0.34743452,  0.18026952,  0.25980872, -0.7567837 ],
       [-0.27643877, -0.93949413,  0.11628805,  0.68984634]],
      dtype=float32)]
[[[-1.8911963   1.6723684   0.2148818   0.35627836]
  [ 0.11691725  0.23798639 -0.00921731 -0.94440436]
  [ 0.34743452  0.18026952  0.25980872 -0.75678

In [114]:

# 借助py_function
# 注意，tf1.12里没有py_function只有py_func差不太多
import tensorflow as tf
tf.reset_default_graph()
print(tf.__version__)
# 在tf1之中配合dataset对multihot样本进行embedding
# 注意featureId一定要从0开始，否则转稀疏矩阵时会丢到该值
num_fields=3
num_features=8
raw_ds=tf.data.Dataset.from_tensor_slices(["1:1 2:3;4 3:6","1:2 2:5 3:7","1:1 2:4 3:7"])

def line_py_parser(line):
    raw_feature_ids=list()
    # 将line.numpy转换为string类型便于处理
    # for field_features in str(line.numpy(), encoding = "utf-8").split(" "):
    #     s=field_features.split(":")
    #     raw_feature_ids.append(s[1])

    for field_features in tf.strings.split([line.numpy()], " ").values:
        print(field_features)
        s=tf.strings.split([field_features],":").values
        raw_feature_ids.append(s[1])

    return raw_feature_ids

def line_tf_parser(line):
    """

    :param line: tensor in string
    :return: 返回的是一个list，每个元素都是一个field的feature_id字符串，用;连接
         借助py_function
    """
    res=tf.py_function(line_py_parser,inp=[line],Tout=[tf.string]*num_fields)

    return res

raw_fields_ds=raw_ds.map(line_tf_parser)
raw_fields_iter=raw_fields_ds.make_initializable_iterator()
raw_fields_item=raw_fields_iter.get_next()

raw_fields_batched_ds=raw_fields_ds.batch(2)
raw_fields_batched_iter=raw_fields_batched_ds.make_initializable_iterator()
raw_fields_batch=raw_fields_batched_iter.get_next() # 每个item为num_fields个shape为[batch_size]，类型string类型

emb_table=tf.get_variable("emb_table",shape=[num_features,4],initializer=tf.truncated_normal_initializer)

def emb_layer(raw_batch):
    embs=list()
    for i in range(num_fields):
        raw_field_i=raw_batch[i]
        raw_field_i=tf.strings.split(raw_field_i,";")
        field_i_features = tf.SparseTensor(indices=raw_field_i.indices,values=tf.strings.to_number(raw_field_i.values,tf.int64),
                                           dense_shape=raw_field_i.dense_shape)
        embs.append(tf.nn.embedding_lookup_sparse(params=emb_table,sp_ids=field_i_features,sp_weights=None))
    emb=tf.stack(embs,axis=1)
    return emb

emb=emb_layer(raw_fields_batch)

with tf.Session() as sess:
    sess.run(raw_fields_iter.initializer)
    sess.run(raw_fields_batched_iter.initializer)
    sess.run(tf.global_variables_initializer())
    raw_fields_batch_v,emb_v=sess.run([raw_fields_batch,emb])
    print(raw_fields_batch_v)
    print(emb_v)


1.15.2
tf.Tensor(b'1:1', shape=(), dtype=string)
tf.Tensor(b'2:3;4', shape=(), dtype=string)
tf.Tensor(b'3:6', shape=(), dtype=string)
tf.Tensor(b'1:2', shape=(), dtype=string)
tf.Tensor(b'2:5', shape=(), dtype=string)
tf.Tensor(b'3:7', shape=(), dtype=string)
(array([b'1', b'2'], dtype=object), array([b'3;4', b'5'], dtype=object), array([b'6', b'7'], dtype=object))
[[[-0.5486503   1.5331244   0.36968952  0.78226274]
  [-0.97738576  1.0572159  -0.2437195  -0.50932246]
  [-0.7055837   0.90787774 -0.23511706 -0.24157326]]

 [[-0.32546532  1.8531755  -0.6947388   0.3313469 ]
  [ 0.36463615 -0.6116369  -0.54370946 -0.5988164 ]
  [-0.4743176  -1.0135776   0.42608678 -1.1530648 ]]]
tf.Tensor(b'1:1', shape=(), dtype=string)
tf.Tensor(b'2:4', shape=(), dtype=string)
tf.Tensor(b'3:7', shape=(), dtype=string)


In [1]:

import tensorflow as tf
from sklearn.datasets import load_iris

tf.reset_default_graph()

iris = load_iris()

features = tf.data.Dataset.from_tensor_slices(iris.data)  # [4,]
labels = tf.data.Dataset.from_tensor_slices(iris.target)  # []

ds = tf.data.Dataset.zip((features, labels))


/Users/dominiczhu/opt/anaconda3/envs/tf112/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/dominiczhu/opt/anaconda3/envs/tf112/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/dominiczhu/opt/anaconda3/envs/tf112/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/dominiczhu/opt/

In [4]:
ds

<ZipDataset shapes: ((4,), ()), types: (tf.float64, tf.int64)>