https://theblog.github.io/post/gini-coefficient-intuitive-explanation/#:~:text=The%20Normalized%20Gini%20coefficient%20is,could%20give%20you%20a%20better


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.interpolate
import scipy.integrate

predictions = [0.9, 0.3, 0.8, 0.75, 0.65, 0.6, 0.78, 0.7, 0.05, 0.4, 0.4, 0.05, 0.5, 0.1, 0.1]
actual = [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [2]:
# Copied from https://www.kaggle.com/c/ClaimPredictionChallenge/discussion/703
def gini(actual, pred, cmpcol = 0, sortcol = 1):
    assert (len(actual) == len(pred))
    all = np.asarray(np.c_[actual, pred, np.arange(len(actual))], dtype=np.float)
    all = all[np.lexsort((all[:, 2], -1 * all[:, 1]))]
    totalLosses = all[:, 0].sum()
    giniSum = all[:, 0].cumsum().sum() / totalLosses

    giniSum -= (len(actual) + 1) / 2.
    return giniSum / len(actual)


def gini_normalized(actual, pred):
    return gini(actual, pred) / gini(actual, actual)

In [3]:
gini_predictions = gini(actual, predictions)
gini_max = gini(actual, actual)
ngini= gini_normalized(actual, predictions)
print('Gini: %.3f, Max. Gini: %.3f, Normalized Gini: %.3f' % (gini_predictions, gini_max, ngini))

Gini: 0.189, Max. Gini: 0.300, Normalized Gini: 0.630


In [10]:
all=np.asarray(np.c_[actual, predictions, np.arange(len(actual))], dtype=np.float)

In [11]:
np.lexsort((all[:, 2], -1 * all[:, 1]))

array([ 0,  2,  6,  3,  7,  4,  5, 12,  9, 10,  1, 13, 14,  8, 11])

In [14]:
new_all=all[np.lexsort((all[:, 2], -1 * all[:, 1]))]

In [16]:
new_all[:,0].cumsum()

array([1., 2., 2., 3., 3., 4., 5., 5., 5., 5., 6., 6., 6., 6., 6.])

In [17]:
new_all



array([[ 1.  ,  0.9 ,  0.  ],
       [ 1.  ,  0.8 ,  2.  ],
       [ 0.  ,  0.78,  6.  ],
       [ 1.  ,  0.75,  3.  ],
       [ 0.  ,  0.7 ,  7.  ],
       [ 1.  ,  0.65,  4.  ],
       [ 1.  ,  0.6 ,  5.  ],
       [ 0.  ,  0.5 , 12.  ],
       [ 0.  ,  0.4 ,  9.  ],
       [ 0.  ,  0.4 , 10.  ],
       [ 1.  ,  0.3 ,  1.  ],
       [ 0.  ,  0.1 , 13.  ],
       [ 0.  ,  0.1 , 14.  ],
       [ 0.  ,  0.05,  8.  ],
       [ 0.  ,  0.05, 11.  ]])