In [70]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()

bn_layer=tf.keras.layers.BatchNormalization(
    axis=-1,
    momentum=0.1, #把动量设小点，让moving mean变化剧烈一些，从而观察效果
    # beta_initializer=tf.ones_initializer,
    # gamma_initializer=tf.ones_initializer,
    # moving_mean_initializer=tf.constant_initializer(0.5),
    # moving_variance_initializer=tf.constant_initializer(0.5)
    trainable=True
)

input_arr=np.reshape(np.arange(0,72),newshape=[2,3,3,4]).astype(np.float32)
input_tensor=tf.constant(input_arr)
output=bn_layer(input_tensor,training=True)

# 在tf1里需要手动进行update滑动平均值，不需要tf.get_collection(tf.GraphKeys.UPDATE_OPS)
update_ops = bn_layer.updates

test_output=bn_layer(input_tensor,training=False)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output_v=sess.run(output)
    print("\ntraining output")
    print(output_v)
    print("\nweights before update")
    print(sess.run(bn_layer.weights))
    sess.run(update_ops)
    print("\nweights after update")
    print(sess.run(bn_layer.weights))
    print("\nnot training output")
    test_output_v=sess.run(test_output)
    print(test_output_v)


training output
[[[[-1.6383542  -1.6383542  -1.6383542  -1.6383542 ]
   [-1.4456066  -1.4456066  -1.4456066  -1.4456066 ]
   [-1.2528591  -1.2528591  -1.2528591  -1.2528591 ]]

  [[-1.0601115  -1.0601115  -1.0601115  -1.0601115 ]
   [-0.867364   -0.867364   -0.867364   -0.867364  ]
   [-0.6746164  -0.6746164  -0.6746164  -0.6746164 ]]

  [[-0.48186886 -0.48186886 -0.48186886 -0.48186886]
   [-0.28912133 -0.28912133 -0.28912133 -0.28912133]
   [-0.09637377 -0.09637377 -0.09637377 -0.09637377]]]


 [[[ 0.09637377  0.09637377  0.09637377  0.09637377]
   [ 0.28912133  0.28912133  0.28912133  0.28912133]
   [ 0.48186886  0.48186886  0.48186886  0.48186886]]

  [[ 0.6746164   0.6746164   0.6746164   0.6746164 ]
   [ 0.867364    0.867364    0.867364    0.867364  ]
   [ 1.0601115   1.0601115   1.0601115   1.0601115 ]]

  [[ 1.2528591   1.2528591   1.2528591   1.2528591 ]
   [ 1.4456066   1.4456066   1.4456066   1.4456066 ]
   [ 1.6383542   1.6383542   1.6383542   1.6383542 ]]]]

weights befor

[<tf.Operation 'batch_normalization/AssignMovingAvg/AssignSubVariableOp' type=AssignSubVariableOp>,
 <tf.Operation 'batch_normalization/AssignMovingAvg_1/AssignSubVariableOp' type=AssignSubVariableOp>]