In [17]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()

input_arr=np.random.random(size=[4,5])
print("==========calc_by_hand==========")
print(np.sum(input_arr,axis=1))

print("==========input_arr==========")
print(input_arr)
input_t=tf.constant(value=input_arr)

dense_layer1=tf.layers.Dense(units=5,
                            kernel_initializer=tf.ones_initializer,
                            kernel_regularizer=tf.keras.regularizers.l2(0.01))
dense_layer2=tf.layers.Dense(units=5,
                            kernel_initializer=tf.ones_initializer,
                            kernel_regularizer=tf.keras.regularizers.l2(0.01))

input_t=dense_layer1(input_t)
out=dense_layer2(input_t)

reg_loss=tf.losses.get_regularization_loss()
reg_losses=tf.losses.get_regularization_losses()
reg_losses_by_add =tf.add_n(reg_losses)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    weight1_v,weight2_v=sess.run([dense_layer1.weights,dense_layer2.weights])
    print("==========weight_v==========")
    print(weight1_v)


    out_v,reg_losses_v,reg_loss_v,reg_losses_by_add_v=sess.run([out,reg_losses,reg_loss,reg_losses_by_add])
    print("==========out_v==========")
    print(out_v)
    print("==========reg_losses_v==========")
    print(reg_losses_v)
    print("==========reg_loss_v==========")
    print(reg_loss_v)
    print("==========reg_losses_by_add==========")
    print(reg_losses_by_add_v)

==========calc_by_hand==========
[1.86911562 2.90886542 2.46298017 2.16922401]
==========input_arr==========
[[0.51842449 0.62931904 0.29434438 0.18034672 0.24668099]
 [0.01490126 0.35448281 0.62182239 0.94284044 0.97481852]
 [0.45476484 0.71701633 0.41868401 0.23790231 0.63461267]
 [0.12543495 0.11359496 0.19558884 0.73851673 0.99608853]]
==========weight_v==========
[array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]]), array([0., 0., 0., 0., 0.])]
==========out_v==========
[[ 9.34557812  9.34557812  9.34557812  9.34557812  9.34557812]
 [14.54432712 14.54432712 14.54432712 14.54432712 14.54432712]
 [12.31490084 12.31490084 12.31490084 12.31490084 12.31490084]
 [10.84612005 10.84612005 10.84612005 10.84612005 10.84612005]]
==========reg_losses_v==========
[0.24999999441206455, 0.24999999441206455]
==========reg_loss_v==========
0.4999999888241291
==========reg_losses_by_add==========
0.4999999

In [13]:
reg_loss


<tf.Tensor 'total_regularization_loss:0' shape=() dtype=float64>

<tf.Tensor 'AddN:0' shape=() dtype=float64>