In [20]:
import tensorflow as tf
mnist=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [28]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])
predictions=model(x_train[:1]).numpy()
predictions

array([[ 0.14412704, -0.1567703 ,  0.07878343,  0.12168525,  0.46115327,
        -0.61312366, -0.46636498, -0.5773218 , -0.7713076 , -0.23343208]],
      dtype=float32)

In [24]:
tf.nn.softmax(predictions).numpy()

array([[0.1936167 , 0.14441672, 0.11193732, 0.0420153 , 0.08921281,
        0.03675685, 0.0845249 , 0.10995886, 0.10656308, 0.08099745]],
      dtype=float32)

In [30]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [31]:
print(y_train[:1])
print(loss_fn(y_train[:1],predictions).numpy())



[5]
2.7869382


In [32]:
model.compile(optimizer="adam",loss=loss_fn,metrics=['accuracy'])
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2901 - accuracy: 0.9152

In [33]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0749 - accuracy: 0.9788


[0.0748659297823906, 0.9787999987602234]

In [34]:
probability_model=tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
probability_model(x_test[:5])


# 从上面的例子可以看出，model的__call__函数对输入的要求
# 都得是具体的一些样本，形如[sample_num,feature_num]这类的
# 而不能是一个dataset
# 但predict和fit等函数的输入要求是dataset，从ML basic里的例子可以看出，必须batch
# 这个例子里没batch是因为输入的形状就是60000,28,28

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.47035223e-09, 1.26527100e-08, 2.72199827e-06, 1.22833968e-04,
        1.86480520e-09, 1.19269203e-06, 4.14220931e-13, 9.99851108e-01,
        9.99241820e-07, 2.10187027e-05],
       [4.22412079e-08, 9.12600837e-04, 9.99039471e-01, 4.56361777e-05,
        2.36812492e-16, 2.14742613e-06, 8.25299935e-08, 1.39923351e-11,
        5.40423777e-08, 3.12450210e-15],
       [6.76903437e-06, 9.99268234e-01, 3.96781870e-05, 1.70868225e-05,
        1.79985709e-05, 1.55872694e-05, 3.95222887e-05, 4.52797656e-04,
        1.41507364e-04, 7.32508681e-07],
       [9.99993443e-01, 6.41744158e-11, 6.03179160e-07, 1.18402701e-08,
        2.36757653e-08, 1.63501340e-07, 5.47888112e-06, 2.14736104e-07,
        2.24060903e-09, 1.20374850e-07],
       [1.22822570e-07, 1.88162055e-08, 1.48659565e-05, 1.46694219e-07,
        9.96759117e-01, 8.18734009e-07, 9.19378977e-07, 1.21066150e-04,
        1.44267347e-06, 3.10147996e-03]], dtype=float32)>