In [3]:
# initializer参数
import tensorflow as tf
dense_layer=tf.keras.layers.Dense(units=2,kernel_initializer=tf.keras.initializers.truncated_normal,bias_initializer=tf.zeros_initializer)
dense_layer.build(input_shape=tf.TensorShape((3,)))
print(dense_layer.trainable_variables)

[<tf.Variable 'kernel:0' shape=(3, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>, <tf.Variable 'bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]


In [47]:
# regularizer参数
# 这个参数会在model.fit过程中起作用，但如果自己只是计算loss，这些个正则项是不会被自动假如的loss里的，这也合理
import tensorflow as tf
import numpy as np
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train=x_train[:100]
y_train=y_train[:100]

input_layer=tf.keras.layers.Input(shape=(28,28),batch_size=None)
flatten=tf.keras.layers.Flatten(input_shape=(28, 28))(input_layer)
dense=tf.keras.layers.Dense(units=10,
                            kernel_initializer=tf.keras.initializers.ones(),
                            bias_initializer=tf.keras.initializers.zeros(),
                            kernel_regularizer=tf.keras.regularizers.l2(0.1))(flatten)
model1=tf.keras.Model(inputs=input_layer,outputs=dense)

# output=model1(x_train[np.newaxis,0])
# loss=tf.keras.losses.sparse_categorical_crossentropy(y_true=y_train[np.newaxis,np.newaxis,0],y_pred=output,from_logits=True)
# print(loss)

model1.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))
model1.fit(x_train,y_train)
print(model1.trainable_variables)


input_layer=tf.keras.layers.Input(shape=(28,28),batch_size=None)
flatten=tf.keras.layers.Flatten(input_shape=(28, 28))(input_layer)
dense=tf.keras.layers.Dense(units=10,
                            kernel_initializer=tf.keras.initializers.ones(),
                            bias_initializer=tf.keras.initializers.zeros())(flatten)
model2=tf.keras.Model(inputs=input_layer,outputs=dense)

# output=model2(x_train[np.newaxis,0])
# loss=tf.keras.losses.sparse_categorical_crossentropy(y_true=y_train[np.newaxis,np.newaxis,0],y_pred=output,from_logits=True)
# print(loss)
model2.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))
model2.fit(x_train,y_train,epochs=1)
print(model2.trainable_variables)

4/4 [==============================] - 0s 664us/step - loss: 784.6102
[<tf.Variable 'dense_46/kernel:0' shape=(784, 10) dtype=float32, numpy=
array([[0.99600023, 0.99600023, 0.99600023, ..., 0.99600023, 0.99600023,
        0.99600023],
       [0.99600023, 0.99600023, 0.99600023, ..., 0.99600023, 0.99600023,
        0.99600023],
       [0.99600023, 0.99600023, 0.99600023, ..., 0.99600023, 0.99600023,
        0.99600023],
       ...,
       [0.99600023, 0.99600023, 0.99600023, ..., 0.99600023, 0.99600023,
        0.99600023],
       [0.99600023, 0.99600023, 0.99600023, ..., 0.99600023, 0.99600023,
        0.99600023],
       [0.99600023, 0.99600023, 0.99600023, ..., 0.99600023, 0.99600023,
        0.99600023]], dtype=float32)>, <tf.Variable 'dense_46/bias:0' shape=(10,) dtype=float32, numpy=
array([ 0.00224127,  0.000154  , -0.00357168, -0.00150153,  0.00083707,
       -0.00394188,  0.00148062, -0.00141218, -0.00156948,  0.00148082

In [5]:
# activation参数
import tensorflow as tf
import numpy as np

input_arr=np.reshape(np.random.random(100),newshape=(10,10)).astype(np.float32) # denselaer
#
#WARNING:tensorflow:Layer dense_1 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because its dtype defaults to floatx.
#If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.
#To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

dense_layer=tf.keras.layers.Dense(units=2,activation=tf.nn.relu)
print(dense_layer(input_arr))


tf.Tensor(
[[0.         0.        ]
 [0.25132638 0.        ]
 [0.6028134  0.        ]
 [0.42676786 0.        ]
 [0.33763117 0.        ]
 [0.16940825 0.15810186]
 [0.68782127 0.        ]
 [1.1767977  0.        ]
 [0.687762   0.        ]
 [1.3696169  0.        ]], shape=(10, 2), dtype=float32)


In [16]:
# output_shape变量
# 这个操作会报错
# 这个方法仅仅在一些情况下可以用
"""
Only applicable if the layer has exactly one input,
    i.e. if it is connected to one incoming layer, or if all inputs
    have the same shape.
"""
input_arr=np.reshape(np.random.random(100),newshape=(10,10)).astype(np.float32)
dense_layer=tf.keras.layers.Dense(units=2,activation=tf.nn.relu)
# dense_layer.build(tf.TensorShape((None,2)))
out=dense_layer(input_arr)
print(out)
dense_layer.input_shape

tf.Tensor(
[[0.49891895 0.        ]
 [0.30264843 0.        ]
 [0.38448787 0.        ]
 [0.30597767 0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.1325359  0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]], shape=(10, 2), dtype=float32)
(10, 2)


In [17]:
# compute_output_shape方法
dense_layer.compute_output_shape(tf.TensorShape((None,2)))

TensorShape([None, 2])

In [3]:
# 取正则化
# tf.keras.layers.Dense的正则化参数只在model+compile里有用
import tensorflow as tf
dense_layer=tf.keras.layers.Dense(units=2,kernel_initializer=tf.keras.initializers.truncated_normal,bias_initializer=tf.zeros_initializer)
dense_layer.build([3,4])
dense_layer.weights


[<tf.Variable 'kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.05108262, -0.0523339 ],
        [ 0.08787255, -0.04206546],
        [ 0.02371662, -0.07115013],
        [ 0.0161767 , -0.07686727]], dtype=float32)>,
 <tf.Variable 'bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]