In [1]:
# emb_layer，输入可以是float，也可以是int哦
import tensorflow as tf
import numpy as np
emb_layer=tf.keras.layers.Embedding(input_dim=4,output_dim=4)
input_arr=np.random.randint(0,3,size=[10,3]).astype(np.float32)

print(emb_layer(input_arr).shape)

(10, 3, 4)


In [2]:

# input_length指的就是输入序列的长度，用于计算输出维度用的，例如下面的例子
# embedding屁股后面跟着个flatten，如果不知道embedding的输出，那么flatten输出的维度也会不定
# 导致后面的dense层无法成功构建
# 如果把input_length关了，model.add(tf.keras.layers.Dense(2))会报错
import tensorflow as tf
import numpy as np
model = tf.keras.Sequential()
emb_layer=tf.keras.layers.Embedding(32, 64, input_length=2)
model.add(emb_layer)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(2))
model.compile()
model.summary()

# 当然如果不使用model.add，而是手动调用layer进行计算的话，这个参数没啥影响
input_arr=np.random.randint(0,3,size=[10,4]).astype(np.float32)
print(emb_layer(input_arr).shape)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 2, 64)             2048      
_________________________________________________________________
flatten (Flatten)            (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 2)                 258       
Total params: 2,306
Trainable params: 2,306
Non-trainable params: 0
_________________________________________________________________
(10, 4, 64)


In [29]:
# mask_zero
import tensorflow as tf
import numpy as np
input_array = np.array([[2,2,0],[0,0,0]])
emb_layer_mask=tf.keras.layers.Embedding(input_dim=32,output_dim=4,mask_zero=True,embeddings_initializer=tf.ones_initializer)
emb_layer_not_mask=tf.keras.layers.Embedding(input_dim=32,output_dim=4,mask_zero=False,embeddings_initializer=tf.ones_initializer)

model= tf.keras.Sequential()
model.add(emb_layer_mask)
model.add(tf.keras.layers.RNN(cell=tf.keras.layers.SimpleRNNCell(units=2,kernel_initializer=tf.ones_initializer,recurrent_initializer=tf.ones_initializer)))
model.compile()
print(model(input_array))

print("\n如果不musk的话")
model= tf.keras.Sequential()
model.add(emb_layer_not_mask)
model.add(tf.keras.layers.RNN(cell=tf.keras.layers.SimpleRNNCell(units=2,kernel_initializer=tf.ones_initializer,recurrent_initializer=tf.ones_initializer)))
model.compile()
print(model(input_array))

print("\n当然如果不使用model.add，而是手动调用layer进行计算的话，这个参数没啥影响")
print(emb_layer_mask(input_array))



tf.Tensor(
[[0.9999878 0.9999878]
 [0.        0.       ]], shape=(2, 2), dtype=float32)

如果不musk的话
tf.Tensor(
[[0.99998784 0.99998784]
 [0.99998784 0.99998784]], shape=(2, 2), dtype=float32)

当然如果不使用model.add，而是手动调用layer进行计算的话，这个参数没啥影响
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)
