In [14]:
# 计算fp，和accuracy差不多 预测为负的正样本
# 经过我多次实验，0代表负样本，除此之外的数都是正样本
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
output_arr=np.random.choice([0,1],size=[2,10])
label_arr=np.random.choice([0,2],size=[2,10])

print("label")
print(label_arr)
print("output")
print(output_arr)

output_batch=tf.data.Dataset.from_tensor_slices(output_arr).make_one_shot_iterator().get_next()
label_batch=tf.data.Dataset.from_tensor_slices(label_arr).make_one_shot_iterator().get_next()

_,update_op=tf.metrics.true_positives(labels=label_batch,predictions=output_batch)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    print(sess.run([update_op]))
    print(sess.run([update_op]))
# print(np.sum(output_arr==label_arr))

label
[[2 0 2 2 0 0 0 2 0 0]
 [0 2 2 2 0 2 0 2 2 0]]
output
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[0.0]
[0.0]
