In [8]:
# 可以看到这个玩意不是简单的算准确度，而是叠加地来算准确度，例如下面的第二个结果，就是两次结果的综合准确度
# update 一次才会更新这个准确度，这个操作会更新count和total，从而更新准确度
import tensorflow as tf
import numpy as np
tf.reset_default_graph()
output_arr=np.random.choice([0,1],size=[2,10])
label_arr=np.random.choice([0,1],size=[2,10])

print(output_arr)
print(label_arr)

output_batch=tf.data.Dataset.from_tensor_slices(output_arr).make_one_shot_iterator().get_next()
label_batch=tf.data.Dataset.from_tensor_slices(label_arr).make_one_shot_iterator().get_next()

accuracy,update_op=tf.metrics.accuracy(labels=label_batch,predictions=output_batch,
                                       updates_collections=tf.GraphKeys.UPDATE_OPS,
                                       name="acc_metric")
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)  # 这个update操作需要定义在bn_layer的call之后，否则会为空

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    print(sess.run([accuracy,update_op]))
    print(sess.run([accuracy,update_op]))
print(np.sum(output_arr==label_arr))

[[0 1 0 0 0 1 0 0 0 0]
 [1 1 1 1 1 0 0 1 1 1]]
[[0 1 0 1 1 0 0 0 0 0]
 [0 0 1 1 1 1 0 1 0 0]]
[0.0, 0.7]
[0.7, 0.6]
12


In [9]:
8/20

In [35]:
running_vars = tf.get_collection(tf.GraphKeys.LOCAL_VARIABLES, scope="acc_metric")


0.4

In [10]:
print(running_vars)
print(update_ops)

[<tf.Variable 'acc_metric/total:0' shape=() dtype=float32_ref>, <tf.Variable 'acc_metric/count:0' shape=() dtype=float32_ref>]
[<tf.Tensor 'acc_metric/update_op:0' shape=() dtype=float32>]
