In [5]:
import tensorflow as tf
import numpy as np

tf.reset_default_graph()
predictions=np.random.choice([0,1,2],size=[2,10])
labels=np.random.choice([0,1,2],size=[2,10])

print(predictions)
print(labels)

# shape: [10,]
predictions_batch=tf.data.Dataset.from_tensor_slices(predictions).make_one_shot_iterator().get_next()
label_batch=tf.data.Dataset.from_tensor_slices(labels).make_one_shot_iterator().get_next()

mean_accuracy,update_op=tf.metrics.mean_per_class_accuracy(
    label_batch, predictions_batch, 3, weights=None, metrics_collections=None,
    updates_collections=None, name=None
)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    print(sess.run([mean_accuracy,update_op]))
    print(sess.run([mean_accuracy,update_op]))

[[2 0 0 1 2 0 0 0 0 0]
 [2 2 0 1 2 2 0 2 0 1]]
[[2 2 2 1 1 2 1 2 2 2]
 [1 0 1 2 1 2 2 1 0 2]]
[0.0, array([0.        , 0.33333334, 0.14285715], dtype=float32)]
[0.15873016, array([0.5       , 0.14285715, 0.18181819], dtype=float32)]


In [19]:
np.sum((predictions==labels) & (labels==1))/np.sum(labels==1)

0.14285714285714285

In [20]:
import tensorflow as tf
import numpy as np

tf.reset_default_graph()
# prediction得是整数
# predictions=np.random.choice([0,1,2],size=[2,10])
predictions=np.random.random(size=[2,10])
labels=np.random.choice([0,1,2],size=[2,10])

print(predictions)
print(labels)

# shape: [10,]
predictions_batch=tf.data.Dataset.from_tensor_slices(predictions).make_one_shot_iterator().get_next()
label_batch=tf.data.Dataset.from_tensor_slices(labels).make_one_shot_iterator().get_next()

mean_accuracy,update_op=tf.metrics.mean_per_class_accuracy(
    label_batch, predictions_batch, 3, weights=None, metrics_collections=None,
    updates_collections=None, name=None
)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    print(sess.run([mean_accuracy,update_op]))
    print(sess.run([mean_accuracy,update_op]))

[[0.18525674 0.79770305 0.43972366 0.14421559 0.59062124 0.66804044
  0.08905546 0.54652941 0.75704681 0.17446025]
 [0.64651885 0.1038739  0.59873095 0.7735293  0.97743608 0.55063135
  0.113937   0.0248686  0.41895029 0.21041744]]
[[2 0 0 1 0 1 1 0 2 0]
 [1 1 0 1 2 2 2 2 2 1]]
[0.0, array([1., 0., 0.], dtype=float32)]
[0.33333334, array([1., 0., 0.], dtype=float32)]
