In [1]:
import tensorflow as tf

In [2]:
#A Tensor is a multi-dimensional array.
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [3]:
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [4]:
import numpy as np

ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())



TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [8]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.config.experimental.list_physical_devices("GPU"))
print(tf.config.experimental.list_physical_devices("CPU"))

print("Is the Tensor on GPU #0:  "),
print(x.device)

Is there a GPU available: 
[]
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
Is the Tensor on GPU #0:  
/job:localhost/replica:0/task:0/device:CPU:0


In [18]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [19]:
for line in ds_file:
  print(line)

tf.Tensor(b'Line 1', shape=(), dtype=string)
tf.Tensor(b'Line 2', shape=(), dtype=string)
tf.Tensor(b'Line 3', shape=(), dtype=string)
tf.Tensor(b'  ', shape=(), dtype=string)


In [20]:
print(ds_tensors)
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
print(ds_tensors) #形状变成了(None,)，即拥有一个轴并且维度为None
for batch in ds_tensors:
  print(batch)

ds_file = ds_file.batch(2)
for line in ds_file:
  print(line)

<TensorSliceDataset shapes: (), types: tf.int32>
<BatchDataset shapes: (None,), types: tf.int32>
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([ 9 25], shape=(2,), dtype=int32)
tf.Tensor([36 16], shape=(2,), dtype=int32)
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)
