In [8]:
import tensorflow as tf
import numpy as np

tf.reset_default_graph()

arr=np.random.random(size=(5,4,3))
var=tf.Variable(arr)

# 每次都找var[,:,]的最大值
arg_max=tf.argmax(var,dimension=1)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    print(sess.run(var))
    print(sess.run(arg_max))

Instructions for updating:
Use the `axis` argument instead
[[[0.42881128 0.97843963 0.81788938]
  [0.62877267 0.6254639  0.64913049]
  [0.94816412 0.62383234 0.54125687]
  [0.32232711 0.61188515 0.02205672]]

 [[0.45885643 0.84915746 0.21923645]
  [0.51230387 0.40338597 0.08298239]
  [0.76400376 0.53787713 0.88241568]
  [0.29841343 0.07493582 0.56499731]]

 [[0.43766069 0.55837455 0.05203133]
  [0.5241584  0.04798583 0.76162789]
  [0.92741429 0.03210417 0.37678932]
  [0.57406292 0.29323323 0.540517  ]]

 [[0.68432966 0.87766322 0.92541588]
  [0.1837013  0.8951878  0.49709861]
  [0.03369085 0.15250067 0.79447526]
  [0.75510349 0.24131871 0.14529661]]

 [[0.23490019 0.20896513 0.90853654]
  [0.79286396 0.66587356 0.62510084]
  [0.33019289 0.08024227 0.12574207]
  [0.89299947 0.37960752 0.51226482]]]
[[2 0 0]
 [2 0 2]
 [2 0 1]
 [3 1 0]
 [3 1 0]]
