In [1]:
import tensorflow as tf
tf.reset_default_graph()


labels=tf.constant([0,0,1,1],dtype=tf.float32)
one = tf.constant(4,shape=labels.shape,dtype=tf.float32)
zero = tf.zeros_like(labels)

label = tf.where(labels <0.5, x=zero, y=one)

with tf.Session() as sess:
    print(sess.run(label))


[0. 0. 4. 4.]


In [11]:
import tensorflow as tf
import numpy as np
tf.reset_default_graph()

ds=tf.data.Dataset.from_tensor_slices(np.random.random(10)).batch(5)
one_sample=ds.make_one_shot_iterator().get_next()

# 由于one_sample大小未知，因此不能使用tf.constant，但可以使用ones_like
one = tf.ones_like(one_sample)*5.1
zero = tf.zeros_like(one_sample)

label = tf.where(one_sample <0.5, x=zero, y=one)

with tf.Session() as sess:
    label,one_sample_v=sess.run([label,one_sample])
    print(one_sample_v)
    print(label)

[0.75139908 0.10957012 0.72011365 0.60434531 0.82567821]
[5.1 0.  5.1 5.1 5.1]


In [12]:
one

<tf.Tensor 'mul:0' shape=(?,) dtype=float64>