In [1]:
import tensorflow as tf
input_ds=tf.data.TextLineDataset("input.csv")
def decode(line):
    row=tf.io.decode_csv(line,["a","b","c","d"])
    number_values=list(map(tf.strings.to_number,row[:-1]))
    return number_values,row[-1]
decode_ds=input_ds.map(decode)
for row in decode_ds:
    print(row)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'hello world \xe4\xbd\xa0\xe5\xa5\xbd'>)
(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 9., 3.], dtype=float32)>, <tf.Tensor: shape=(), dtype=string, numpy=b'hello ji hei ji'>)
