In [1]:
import tensorflow as tf

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from sklearn.model_selection import train_test_split

import unicodedata
import re
import numpy as np
import os
import io
import time

In [2]:
# Download the file
path_to_zip = tf.keras.utils.get_file(
    'spa-eng.zip', origin='http://storage.googleapis.com/download.tensorflow.org/data/spa-eng.zip',
    extract=True)

path_to_file = .dirname(path_to_zip)+"/spa-eng/spa.txt"

In [3]:
# Converts the unicode file to ascii
def unicode_to_ascii(s):
  return ''.join(c for c in unicodedata.normalize('NFD', s)
      if unicodedata.category(c) != 'Mn')


def preprocess_sentence(w):
  w = unicode_to_ascii(w.lower().strip())

  # creating a space between a word and the punctuation following it
  # eg: "he is a boy." => "he is a boy ."
  # Reference:- https://stackoverflow.com/questions/3645931/python-padding-punctuation-with-white-spaces-keeping-punctuation
  w = re.sub(r"([?.!,¿])", r" \1 ", w)
  w = re.sub(r'[" "]+', " ", w)

  # replacing everything with space except (a-z, A-Z, ".", "?", "!", ",")
  w = re.sub(r"[^a-zA-Z?.!,¿]+", " ", w)

  w = w.strip()

  # adding a start and an end token to the sentence
  # so that the model know when to start and stop predicting.
  w = '<start> ' + w + ' <end>'
  return w

In [4]:
en_sentence = u"May I borrow this book?"
sp_sentence = u"¿Puedo tomar prestado este libro?"
print(preprocess_sentence(en_sentence))
print(preprocess_sentence(sp_sentence).encode('utf-8'))

<start> may i borrow this book ? <end>
b'<start> \xc2\xbf puedo tomar prestado este libro ? <end>'


In [5]:
s = 'bla. bla? bla.bla! bla...'
import re
s = re.sub('([.,!?()])', r' \1 ', s)
print(s)
s = re.sub('\s{2,}', ' ', s)
print(s)

bla .  bla ?  bla . bla !  bla .  .  . 
bla . bla ? bla . bla ! bla . . . 


In [6]:
# 1. Remove the accents
# 2. Clean the sentences
# 3. Return word pairs in the format: [ENGLISH, SPANISH]
def create_dataset(path, num_examples):
  lines = io.open(path, encoding='UTF-8').read().strip().split('\n')

  word_pairs = [[preprocess_sentence(w) for w in l.split('\t')]  for l in lines[:num_examples]]

  return zip(*word_pairs)

In [7]:
en, sp = create_dataset(path_to_file, None)
print(en[-1])
print(sp[-1])

<start> if you want to sound like a native speaker , you must be willing to practice saying the same sentence over and over in the same way that banjo players practice the same phrase over and over until they can play it correctly and at the desired tempo . <end>
<start> si quieres sonar como un hablante nativo , debes estar dispuesto a practicar diciendo la misma frase una y otra vez de la misma manera en que un musico de banjo practica el mismo fraseo una y otra vez hasta que lo puedan tocar correctamente y en el tiempo esperado . <end>


In [8]:
# 英文和西班牙语是通过\t分割的
lines = io.open(path_to_file, encoding='UTF-8').read().strip().split('\n')
lines[:None]

['Go.\tVe.',
 'Go.\tVete.',
 'Go.\tVaya.',
 'Go.\tVáyase.',
 'Hi.\tHola.',
 'Run!\t¡Corre!',
 'Run.\tCorred.',
 'Who?\t¿Quién?',
 'Fire!\t¡Fuego!',
 'Fire!\t¡Incendio!',
 'Fire!\t¡Disparad!',
 'Help!\t¡Ayuda!',
 'Help!\t¡Socorro! ¡Auxilio!',
 'Help!\t¡Auxilio!',
 'Jump!\t¡Salta!',
 'Jump.\tSalte.',
 'Stop!\t¡Parad!',
 'Stop!\t¡Para!',
 'Stop!\t¡Pare!',
 'Wait!\t¡Espera!',
 'Wait.\tEsperen.',
 'Go on.\tContinúa.',
 'Go on.\tContinúe.',
 'Hello!\tHola.',
 'I ran.\tCorrí.',
 'I ran.\tCorría.',
 'I try.\tLo intento.',
 'I won!\t¡He ganado!',
 'Oh no!\t¡Oh, no!',
 'Relax.\tTomátelo con soda.',
 'Smile.\tSonríe.',
 'Attack!\t¡Al ataque!',
 'Attack!\t¡Atacad!',
 'Get up.\tLevanta.',
 'Go now.\tVe ahora mismo.',
 'Got it!\t¡Lo tengo!',
 'Got it?\t¿Lo pillas?',
 'Got it?\t¿Entendiste?',
 'He ran.\tÉl corrió.',
 'Hop in.\tMétete adentro.',
 'Hug me.\tAbrázame.',
 'I fell.\tMe caí.',
 'I know.\tYo lo sé.',
 'I left.\tSalí.',
 'I lied.\tMentí.',
 'I lost.\tPerdí.',
 'I quit.\tDimito.',
 'I quit.\t

In [9]:
def tokenize(lang):
  lang_tokenizer = tf.keras.preprocessing.text.Tokenizer(
      filters='') # 这个可是个好玩意，将文本映射为编码 只不过无法处理tensor
  lang_tokenizer.fit_on_texts(lang) # fit

  tensor = lang_tokenizer.texts_to_sequences(lang) #将文本映射成词

  tensor = tf.keras.preprocessing.sequence.pad_sequences(tensor,
                                                         padding='post')

  return tensor, lang_tokenizer

def load_dataset(path, num_examples=None):
  # creating cleaned input, output pairs
  targ_lang, inp_lang = create_dataset(path, num_examples)

  input_tensor, inp_lang_tokenizer = tokenize(inp_lang)
  target_tensor, targ_lang_tokenizer = tokenize(targ_lang)

  return input_tensor, target_tensor, inp_lang_tokenizer, targ_lang_tokenizer

In [10]:
# Try experimenting with the size of that dataset
num_examples = 30000
input_tensor, target_tensor, inp_lang, targ_lang = load_dataset(path_to_file, num_examples)

# Calculate max_length of the target tensors
max_length_targ, max_length_inp = target_tensor.shape[1], input_tensor.shape[1]

In [11]:
print(input_tensor)
print(inp_lang.index_word)

[[   1  135    3 ...    0    0    0]
 [   1  293    3 ...    0    0    0]
 [   1  595    3 ...    0    0    0]
 ...
 [   1   18 9413 ...    0    0    0]
 [   1   63 2490 ...    0    0    0]
 [   1   23 2175 ...    0    0    0]]
{1: '<start>', 2: '<end>', 3: '.', 4: 'tom', 5: '?', 6: '¿', 7: 'es', 8: 'no', 9: 'el', 10: 'a', 11: 'que', 12: 'me', 13: 'la', 14: 'de', 15: 'un', 16: 'esta', 17: 'se', 18: 'lo', 19: 'mi', 20: 'en', 21: 'una', 22: 'por', 23: 'te', 24: 'estoy', 25: 'ella', 26: 'yo', 27: '!', 28: 'eso', 29: 'le', 30: 'esto', 31: 'tu', 32: ',', 33: 'los', 34: 'aqui', 35: 'soy', 36: 'muy', 37: 'tengo', 38: 'puedo', 39: 'las', 40: 'gusta', 41: 'mary', 42: 'tiene', 43: 'son', 44: 'con', 45: 'como', 46: 'quien', 47: 'estaba', 48: 'su', 49: 'este', 50: 'favor', 51: 'estas', 52: 'eres', 53: 'quiero', 54: 'ellos', 55: 'fue', 56: 'bien', 57: 'casa', 58: 'ahora', 59: 'tomas', 60: 'donde', 61: 'mas', 62: 'estan', 63: 'nos', 64: 'he', 65: 'solo', 66: 'puede', 67: 'ha', 68: 'era', 69: 'todos'

In [12]:

# Creating training and validation sets using an 80-20 split
input_tensor_train, input_tensor_val, target_tensor_train, target_tensor_val = train_test_split(input_tensor, target_tensor, test_size=0.2)

# Show length
print(len(input_tensor_train), len(target_tensor_train), len(input_tensor_val), len(target_tensor_val))


24000 24000 6000 6000


In [13]:
def convert(lang, tensor):
  for t in tensor:
    if t!=0:
      print ("%d ----> %s" % (t, lang.index_word[t]))

print ("Input Language; index to word mapping")
convert(inp_lang, input_tensor_train[0])
print ()
print ("Target Language; index to word mapping")
convert(targ_lang, target_tensor_train[0])

Input Language; index to word mapping
1 ----> <start>
4 ----> tom
104 ----> sabe
11 ----> que
41 ----> mary
903 ----> mintio
3 ----> .
2 ----> <end>

Target Language; index to word mapping
1 ----> <start>
5 ----> tom
200 ----> knows
45 ----> mary
548 ----> lied
3 ----> .
2 ----> <end>


In [14]:
BUFFER_SIZE = len(input_tensor_train)
BATCH_SIZE = 64
steps_per_epoch = len(input_tensor_train)//BATCH_SIZE
embedding_dim = 256
units = 1024
vocab_inp_size = len(inp_lang.word_index)+1
vocab_tar_size = len(targ_lang.word_index)+1

dataset = tf.data.Dataset.from_tensor_slices((input_tensor_train, target_tensor_train)).shuffle(BUFFER_SIZE)
dataset = dataset.batch(BATCH_SIZE, drop_remainder=True)

In [15]:
example_input_batch, example_target_batch = next(iter(dataset))
example_input_batch.shape, example_target_batch.shape

(TensorShape([64, 16]), TensorShape([64, 11]))

In [16]:
class Encoder(tf.keras.Model):
  def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
    super(Encoder, self).__init__()
    self.batch_sz = batch_sz
    self.enc_units = enc_units
    self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
    self.gru = tf.keras.layers.GRU(self.enc_units,
                                   return_sequences=True,
                                   return_state=True,
                                   recurrent_initializer='glorot_uniform')

  def call(self, x, hidden):
    x = self.embedding(x)
    output, state = self.gru(x, initial_state = hidden)
    return output, state

  def initialize_hidden_state(self):
    return tf.zeros((self.batch_sz, self.enc_units))

encoder = Encoder(vocab_inp_size, embedding_dim, units, BATCH_SIZE)

# sample input
sample_hidden = encoder.initialize_hidden_state()
sample_output, sample_hidden = encoder(example_input_batch, sample_hidden)
print ('Encoder output shape: (batch size, sequence length, units) {}'.format(sample_output.shape))
print ('Encoder Hidden state shape: (batch size, units) {}'.format(sample_hidden.shape))


Encoder output shape: (batch size, sequence length, units) (64, 16, 1024)
Encoder Hidden state shape: (batch size, units) (64, 1024)


In [17]:
class BahdanauAttention(tf.keras.layers.Layer):
  def __init__(self, units):
    super(BahdanauAttention, self).__init__()
    self.W1 = tf.keras.layers.Dense(units)
    self.W2 = tf.keras.layers.Dense(units)
    self.V = tf.keras.layers.Dense(1)

  def call(self, query, values):
    # 这个 query代表的就是最后一次输入，values代表的就是之前的那些个hidden layers输出
    # query hidden state shape == (batch_size, hidden size)
    # query_with_time_axis shape == (batch_size, 1, hidden size)
    # values shape == (batch_size, max_len, hidden size)
    # we are doing this to broadcast addition along the time axis to calculate the score
    query_with_time_axis = tf.expand_dims(query, 1)

    # score shape == (batch_size, max_length, 1)
    # we get 1 at the last axis because we are applying score to self.V
    # the shape of the tensor before applying self.V is (batch_size, max_length, units)
    # dense层都是对最后一个轴作为一批的输入，然后计算一个unit大小的轴
    # self.W1(query_with_time_axis)输出形状是(batch_size, 1, units)
    # self.W2(values)输出形状是(batch_size, max_len, units)
    # print(self.W1(query_with_time_axis).shape)
    # print(self.W2(values).shape)
    # print(tf.nn.tanh(
    #     self.W1(query_with_time_axis) + self.W2(values)).shape)
    score = self.V(tf.nn.tanh(
        self.W1(query_with_time_axis) + self.W2(values)))

    # attention_weights shape == (batch_size, max_length, 1)
    attention_weights = tf.nn.softmax(score, axis=1)

    # context_vector shape after sum == (batch_size, hidden_size)
    context_vector = attention_weights * values # 这个的输出是(batch_size, max_len, hidden size)
    # print(context_vector.shape)
    context_vector = tf.reduce_sum(context_vector, axis=1) # 在sequence这个axis上求和，相当于对每个隐向量加权求和了

    return context_vector, attention_weights


In [18]:
attention_layer = BahdanauAttention(10)
attention_result, attention_weights = attention_layer(sample_hidden, sample_output)

print("Attention result shape: (batch size, units) {}".format(attention_result.shape))
print("Attention weights shape: (batch_size, sequence_length, 1) {}".format(attention_weights.shape))



Attention result shape: (batch size, units) (64, 1024)
Attention weights shape: (batch_size, sequence_length, 1) (64, 16, 1)


In [19]:
class Decoder(tf.keras.Model):
  def __init__(self, vocab_size, embedding_dim, dec_units, batch_sz):
    super(Decoder, self).__init__()
    self.batch_sz = batch_sz
    self.dec_units = dec_units
    self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
    self.gru = tf.keras.layers.GRU(self.dec_units,
                                   return_sequences=True,
                                   return_state=True,
                                   recurrent_initializer='glorot_uniform')
    self.fc = tf.keras.layers.Dense(vocab_size)

    # used for attention
    self.attention = BahdanauAttention(self.dec_units)

  def call(self, x, hidden, enc_output):
    # hidden是当前decoder的隐向量，相当于状态，x是当前的输入词，是一个(batch_size,1)的东西
    # enc_output是encoder的输出用于计算注意力
    # enc_output shape == (batch_size, max_length, hidden_size)
    # context_vector的形状是(batch_size,attention_units)
    context_vector, attention_weights = self.attention(hidden, enc_output)

    # x shape after passing through embedding == (batch_size, 1, embedding_dim)
    x = self.embedding(x)

    # x shape after concatenation == (batch_size, 1, embedding_dim + hidden_size)
    x = tf.concat([tf.expand_dims(context_vector, 1), x], axis=-1)

    # passing the concatenated vector to the GRU
    output, state = self.gru(x)

    # output shape == (batch_size * 1, hidden_size)
    output = tf.reshape(output, (-1, output.shape[2]))

    # output shape == (batch_size, vocab)
    x = self.fc(output)

    return x, state, attention_weights

In [20]:
decoder = Decoder(vocab_tar_size, embedding_dim, units, BATCH_SIZE)

sample_decoder_output, _, _ = decoder(tf.random.uniform((BATCH_SIZE, 1)),
                                      sample_hidden, sample_output)

print ('Decoder output shape: (batch_size, vocab size) {}'.format(sample_decoder_output.shape))

Decoder output shape: (batch_size, vocab size) (64, 4935)


In [27]:
optimizer = tf.keras.optimizers.Adam()
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True, reduction='none')

def loss_function(real, pred):
  """

  :param real: (batch_size,)  相当于整个batch里第t个词的数据
  :param pred: (batch_size,vocab_size)
  :return:
  """
  print(real.shape)
  print(pred.shape)
  mask = tf.math.logical_not(tf.math.equal(real, 0))
  # 为啥需要有这一步呢，这是因为如果target 为0，那这个词就是空词，不该算损失的。
  print(mask)
  loss_ = loss_object(real, pred)

  mask = tf.cast(mask, dtype=loss_.dtype)
  loss_ *= mask

  return tf.reduce_mean(loss_)

In [28]:
mask = tf.math.logical_not(tf.math.equal([0,1], 0))
tf.cast(mask, dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>

In [29]:
@tf.function
def train_step(inp, targ, enc_hidden):
  # 输入就是一个batch
  loss = 0

  with tf.GradientTape() as tape:
    # 一次吧一个batch的文字序列喂给encoder得到完整的hidden状态
    enc_output, enc_hidden = encoder(inp, enc_hidden)

    dec_hidden = enc_hidden
    # 一次输入一列的word，dec_input记录的就是整个batch里第t个词的数据，喂给decoder
    dec_input = tf.expand_dims([targ_lang.word_index['<start>']] * BATCH_SIZE, 1)

    # Teacher forcing - feeding the target as the next input
    for t in range(1, targ.shape[1]):
      # passing enc_output to the decoder
      predictions, dec_hidden, _ = decoder(dec_input, dec_hidden, enc_output)

      loss += loss_function(targ[:, t], predictions)

      # using teacher forcing
      dec_input = tf.expand_dims(targ[:, t], 1)
  print(targ.shape)
  batch_loss = (loss / int(targ.shape[1]))

  variables = encoder.trainable_variables + decoder.trainable_variables

  gradients = tape.gradient(loss, variables)

  optimizer.apply_gradients(zip(gradients, variables))

  return batch_loss

In [30]:
EPOCHS = 10

for epoch in range(EPOCHS):
  start = time.time()

  enc_hidden = encoder.initialize_hidden_state()
  total_loss = 0

  for (batch, (inp, targ)) in enumerate(dataset.take(steps_per_epoch)):
    batch_loss = train_step(inp, targ, enc_hidden)
    total_loss += batch_loss

    if batch % 100 == 0:
      print('Epoch {} Batch {} Loss {:.4f}'.format(epoch + 1,
                                                   batch,
                                                   batch_loss.numpy()))
    break
  break
  # saving (checkpoint) the model every 2 epochs
  # if (epoch + 1) % 2 == 0:
  #   checkpoint.save(file_prefix = checkpoint_prefix)

  print('Epoch {} Loss {:.4f}'.format(epoch + 1,
                                      total_loss / steps_per_epoch))
  print('Time taken for 1 epoch {} sec\n'.format(time.time() - start))

(64,)
(64, 4935)
Tensor("LogicalNot:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_1:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_2:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_3:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_4:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_5:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_6:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_7:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_8:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_9:0", shape=(64,), dtype=bool)
(64, 11)
(64,)
(64, 4935)
Tensor("LogicalNot:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_1:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_2:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_3:0", shape=(64,), dtype=bool)
(64,)
(64, 4935)
Tensor("LogicalNot_4:0", shape=(64,), dt

In [94]:
targ[:, 1]

<tf.Tensor: shape=(64,), dtype=int32, numpy=
array([  13,   20,    4,    4,   62,    4,    4, 1550,   25,    6,    4,
        132,   57,    4,  882,    4,   20,   30,   27,    4,  279,   86,
         28,   86,   27,    6,   24,   25,    5,    5,    4,    4,   24,
        267,    5,   10,   88,    6,   94,    6,   61,   24,   25,  157,
         27,    5,   22,  403,   21,    4,  188,   53,   10,    5,   13,
         14,    4,   13,    4,   16,    4,    4,   56,    4], dtype=int32)>