In [1]:
import numpy as np
import tensorflow as tf

arr=np.random.random(size=[3,4])
print(arr)
print(tf.argmax(arr,axis=1))



[[0.52679796 0.62622236 0.04632462 0.50377377]
 [0.33964578 0.04053857 0.39030815 0.64431113]
 [0.48139936 0.12999047 0.89393424 0.93780864]]
tf.Tensor([1 3 3], shape=(3,), dtype=int64)
