In [1]:
# tf.GradientTape

import tensorflow as tf

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(2,input_shape=(None,5)))
input_x = tf.reshape(tf.range(0,10),(2,5))

with tf.GradientTape() as tape1:
    output_y1=model(input_x)
print(output_y1)
print(model.trainable_variables)
grad1 = tape1.gradient(output_y1,model.trainable_variables)
print(grad1)

print("=================================")
model_not_trained=tf.keras.Sequential()
model_not_trained.add(tf.keras.layers.Dense(2,input_shape=(None,5),trainable=False))
with tf.GradientTape() as tape2:
    output_y2=model_not_trained(input_x)
print(output_y2)
print(model_not_trained.trainable_variables) # empty
grad2 = tape2.gradient(output_y2,model_not_trained.trainable_variables)
print(grad2) # so it's empty too

print("=================================")

x = tf.constant(3.0)
with tf.GradientTape() as g:
  g.watch(x)
  y = x * x
dy_dx = g.gradient(y, x)
print(dy_dx)

# 这个可以用来计算某一个公式的梯度，只不过需要手动watch一下自变量


print("=================================")



tf.Tensor(
[[  5.6075783  -6.7396502]
 [ 14.689421  -22.427818 ]], shape=(2, 2), dtype=float32)
[<tf.Variable 'dense/kernel:0' shape=(5, 2) dtype=float32, numpy=
array([[-0.5221443 , -0.80656815],
       [ 0.8729869 , -0.51005256],
       [ 0.46929502, -0.1005199 ],
       [ 0.18892133, -0.8534138 ],
       [ 0.8073094 , -0.86707914]], dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]
[<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 5.,  5.],
       [ 7.,  7.],
       [ 9.,  9.],
       [11., 11.],
       [13., 13.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]
tf.Tensor(
[[-0.6295054  -1.2359316 ]
 [ 0.06381881 -4.8461185 ]], shape=(2, 2), dtype=float32)
[]
[]
tf.Tensor(6.0, shape=(), dtype=float32)


In [2]:
import tensorflow as tf

@tf.custom_gradient
def log1pexp(x):
  e = tf.exp(x)
  def grad(dy):
    print(dy)
    return dy * (1 - 1 / (1 + e))
  return tf.math.log(1 + e), grad


# 自定义梯度的写法，返回一个结果，第二个参数是根据结果计算梯度的方法
# 具体咋用看api介绍吧，急着出去玩了

def grad_log1pexp(x):
  with tf.GradientTape() as tape:
    tape.watch(x)
    value = log1pexp(x)
  
  return tape.gradient(value, x)

grad_log1pexp(tf.constant(100.)).numpy()

grad_log1pexp(tf.constant(.1)).numpy()


tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


0.52497923