In [4]:
# tf.gather_nd
import tensorflow as tf
import numpy as np

arr=np.reshape(np.arange(0,60),newshape=(3,4,5))

print("下面两者操作相同")
print("tensor结果")
print(tf.gather_nd(arr,indices=[[2],[1]]))
print("arr切片结果")
print(arr[[2,1],:,:])



下面两者操作相同
tensor结果
tf.Tensor(
[[[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]], shape=(2, 4, 5), dtype=int64)
arr切片结果
[[[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]

下面两者操作相同
tensor结果
tf.Tensor(
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]], shape=(4, 5), dtype=int64)
arr切片结果
[[10 11 12 13 14]
 [30 31 32 33 34]
 [50 51 52 53 54]]


In [5]:
import tensorflow as tf
import numpy as np
arr=np.reshape(np.arange(0,60),newshape=(3,4,5))
print("\n下面两者操作相同")
print("tensor结果")
print(tf.gather_nd(arr,indices=[[2,1],[1,2]]))
print("arr切片结果")
print("相当于arr[2,1,:]拼arr[1,2,:]")
print(arr[[2,1],[1,2]])


下面两者操作相同
tensor结果
tf.Tensor(
[[45 46 47 48 49]
 [30 31 32 33 34]], shape=(2, 5), dtype=int64)
arr切片结果
[[45 46 47 48 49]
 [30 31 32 33 34]]


In [20]:
import tensorflow as tf
import numpy as np
arr=np.reshape(np.arange(0,60),newshape=(3,4,5))
print("\n下面两者操作相同")
print("tensor结果")
print(tf.gather_nd(arr,indices=[[[2,1],[1,2]]]))
print("arr切片结果")
print(np.expand_dims(arr[[2,1],[1,2]],axis=0))


下面两者操作相同
tensor结果
tf.Tensor(
[[[45 46 47 48 49]
  [30 31 32 33 34]]], shape=(1, 2, 5), dtype=int64)
arr切片结果
[[[45 46 47 48 49]
  [30 31 32 33 34]]]


In [21]:
import tensorflow as tf
import numpy as np
arr=np.reshape(np.arange(0,60),newshape=(3,4,5))
print("\n下面两者操作相同")
print("tensor结果")
print(tf.gather_nd(arr,indices=[[[2,1]],[[1,2]]]))
print("arr切片结果")
print(np.expand_dims(arr[[2,1],[1,2]],axis=1))


下面两者操作相同
tensor结果
tf.Tensor(
[[[45 46 47 48 49]]

 [[30 31 32 33 34]]], shape=(2, 1, 5), dtype=int64)
arr切片结果
[[[45 46 47 48 49]]

 [[30 31 32 33 34]]]


In [36]:
# batch_dims
import tensorflow as tf
import numpy as np
arr=np.reshape(np.arange(0,60),newshape=(3,4,5))
print("\n下面两者操作相同")
print("tensor结果")
print(tf.gather_nd(arr,indices=[[0,1],[1,2],[1,3]],batch_dims=1))
print("arr切片结果")
print(arr[0,0,1])
print(arr[1,1,2])
print(arr[2,1,3])


下面两者操作相同
tensor结果
tf.Tensor([ 1 27 48], shape=(3,), dtype=int64)
arr切片结果
1
27
48


In [41]:
# batch_dims
import tensorflow as tf
import numpy as np
arr=np.reshape(np.arange(0,60),newshape=(3,4,5))
print("\n下面两者操作相同")
print("tensor结果")
print(tf.gather_nd(arr,indices=[[0,1],[1,2],[1,3]],batch_dims=0))
print("arr切片结果")
print(arr[0,1,:])
print(arr[1,2,:])
print(arr[1,3,:])



下面两者操作相同
tensor结果
tf.Tensor(
[[ 5  6  7  8  9]
 [30 31 32 33 34]
 [35 36 37 38 39]], shape=(3, 5), dtype=int64)
arr切片结果
[5 6 7 8 9]
[30 31 32 33 34]
[35 36 37 38 39]
