In [5]:
# tf.gather
import tensorflow as tf
import numpy as np

arr=np.reshape(np.arange(0,60),newshape=(3,4,5))

print("下面两者操作相同")
print("tensor结果")
print(tf.gather(arr,indices=2))
print("arr切片结果")
print(arr[2,:,:])

print("\n下面两者操作相同")
print("tensor结果")
print(tf.gather(arr,indices=2,axis=1))
print("arr切片结果")
print(arr[:,2,:])

下面两者操作相同
tensor结果
tf.Tensor(
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]], shape=(4, 5), dtype=int64)
arr切片结果
[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]

下面两者操作相同
tensor结果
tf.Tensor(
[[10 11 12 13 14]
 [30 31 32 33 34]
 [50 51 52 53 54]], shape=(3, 5), dtype=int64)
arr切片结果
[[10 11 12 13 14]
 [30 31 32 33 34]
 [50 51 52 53 54]]


其实就是`tf`不支持像对`np.ndarr`那样的`arr[:,2,:]`的操作，只能通过`tf.gather`来实现
`axis`就是指定从哪个轴上取

In [7]:
# tf.gather 的indices参数作用
import tensorflow as tf
import numpy as np

arr=np.reshape(np.arange(0,60),newshape=(3,4,5))

print("\n下面两者操作相同")
print("tensor结果")
print(tf.gather(arr,indices=[1,2],axis=1))
print("arr切片结果")
print(arr[:,[1,2],:])

print("\n下面两者操作相同")
print("tensor结果")
print(tf.gather(arr,indices=[1,1,2],axis=1))
print("arr切片结果")
print(arr[:,[1,1,2],:])



下面两者操作相同
tensor结果
tf.Tensor(
[[[ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[25 26 27 28 29]
  [30 31 32 33 34]]

 [[45 46 47 48 49]
  [50 51 52 53 54]]], shape=(3, 2, 5), dtype=int64)
arr切片结果
[[[ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[25 26 27 28 29]
  [30 31 32 33 34]]

 [[45 46 47 48 49]
  [50 51 52 53 54]]]

下面两者操作相同
tensor结果
tf.Tensor(
[[[ 5  6  7  8  9]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[25 26 27 28 29]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[45 46 47 48 49]
  [45 46 47 48 49]
  [50 51 52 53 54]]], shape=(3, 3, 5), dtype=int64)
arr切片结果
[[[ 5  6  7  8  9]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[25 26 27 28 29]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[45 46 47 48 49]
  [45 46 47 48 49]
  [50 51 52 53 54]]]
