In [6]:
# tf.matmul 矩阵相乘
import numpy as np
import tensorflow as tf
arr1=np.reshape(np.arange(0,120),newshape=(2,3,4,5))
arr2=np.reshape(np.arange(-120,0),newshape=(2,3,5,4))
res=tf.matmul(arr1,arr2)

print("矩阵相乘的结果")
print(res)
print(res.shape)

print("\n结果的计算规则")
print(res[0,0,:,:])
print(np.matmul(arr1[0,0,:,:],arr2[0,0,:,:]))
print("把最后两个轴作为矩阵，进行相乘")

矩阵相乘的结果
tf.Tensor(
[[[[ -1080  -1070  -1060  -1050]
   [ -3880  -3845  -3810  -3775]
   [ -6680  -6620  -6560  -6500]
   [ -9480  -9395  -9310  -9225]]

  [[-10080  -9970  -9860  -9750]
   [-12380 -12245 -12110 -11975]
   [-14680 -14520 -14360 -14200]
   [-16980 -16795 -16610 -16425]]

  [[-15080 -14870 -14660 -14450]
   [-16880 -16645 -16410 -16175]
   [-18680 -18420 -18160 -17900]
   [-20480 -20195 -19910 -19625]]]


 [[[-16080 -15770 -15460 -15150]
   [-17380 -17045 -16710 -16375]
   [-18680 -18320 -17960 -17600]
   [-19980 -19595 -19210 -18825]]

  [[-13080 -12670 -12260 -11850]
   [-13880 -13445 -13010 -12575]
   [-14680 -14220 -13760 -13300]
   [-15480 -14995 -14510 -14025]]

  [[ -6080  -5570  -5060  -4550]
   [ -6380  -5845  -5310  -4775]
   [ -6680  -6120  -5560  -5000]
   [ -6980  -6395  -5810  -5225]]]], shape=(2, 3, 4, 4), dtype=int64)
(2, 3, 4, 4)

结果的计算规则
tf.Tensor(
[[-1080 -1070 -1060 -1050]
 [-3880 -3845 -3810 -3775]
 [-6680 -6620 -6560 -6500]
 [-9480 -9395 -9310 -9225]