In [2]:
import tensorflow as tf
import numpy as np

arr=np.reshape(np.arange(0,60),[2,3,2,5])
tf_res=tf.reduce_sum(arr,axis=[1])
print("tf.reduce_sum手动计算结果")
print(tf_res)

print("\n手动计算结果")
# 是对应位置相加
artifical_res=arr[:,0,:,:]+arr[:,1,:,:]+arr[:,2,:,:]
print(artifical_res)

print("\n 对应位置相加")
print(np.sum(arr[0,:,0,0]))
print(tf_res[0,0,0])

tf.reduce_sum手动计算结果
tf.Tensor(
[[[ 30  33  36  39  42]
  [ 45  48  51  54  57]]

 [[120 123 126 129 132]
  [135 138 141 144 147]]], shape=(2, 2, 5), dtype=int64)

手动计算结果
[[[ 30  33  36  39  42]
  [ 45  48  51  54  57]]

 [[120 123 126 129 132]
  [135 138 141 144 147]]]

 对应位置相加
30
tf.Tensor(30, shape=(), dtype=int64)


In [7]:
# axis作用
import tensorflow as tf
import numpy as np
arr=np.reshape(np.arange(0,60),[2,3,2,5])
tf_res=tf.reduce_sum(arr,axis=[1,2])
print("tf.reduce_sum手动计算结果")
print(tf_res)

print("\n手动计算结果")
artifical_res=arr[:,0,0,:]+arr[:,1,0,:]+arr[:,2,0,:]+arr[:,0,1,:]+arr[:,1,1,:]+arr[:,2,1,:]
print(artifical_res)

tf.reduce_sum手动计算结果
tf.Tensor(
[[ 75  81  87  93  99]
 [255 261 267 273 279]], shape=(2, 5), dtype=int64)

手动计算结果
[[ 75  81  87  93  99]
 [255 261 267 273 279]]
