In [1]:
import tensorflow as tf

# tf.split

x = tf.Variable(tf.reshape(tf.range(0,30),(5,6)))

# Split `x` into 3 tensors along dimension 1
print("along axis 0")
l = tf.split(x, num_or_size_splits=5, axis=0)
print(l)
print("\nalong axis 1")
l = tf.split(x, num_or_size_splits=3, axis=1)
print(l)

print("\nnum_or_size_splits is a list")
l = tf.split(x, num_or_size_splits=[1,2,3], axis=1)
print(l)

print("\nalong axis 0")
x = tf.Variable(tf.range(0,30))
l = tf.split(x, num_or_size_splits=30, axis=0)
print(l)


along axis 0
[<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 1, 2, 3, 4, 5]], dtype=int32)>, <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[ 6,  7,  8,  9, 10, 11]], dtype=int32)>, <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[12, 13, 14, 15, 16, 17]], dtype=int32)>, <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[18, 19, 20, 21, 22, 23]], dtype=int32)>, <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[24, 25, 26, 27, 28, 29]], dtype=int32)>]

along axis 1
[<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25]], dtype=int32)>, <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27]], dtype=int32)>, <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23],
       [28, 29]], dtype=int32)>]

num_or_size_splits is a list
[<tf.Tensor: shape=(5, 1), dtype=int